version: '3'

services:
  redis:
    image: redis:alpine
    env_file:
      - .env.docker
    restart: on-failure
    ports:
      - "6379:6379"
  db:
    image: postgres:14-alpine
    env_file:
      - .env.docker
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    ports:
      - "5432:5432"
  bot:
    env_file:
      - .env.docker
    build: .
    restart: always
    volumes:
      - logs:/app/bot/data/logs
    depends_on:
      - db
      - redis

volumes:
  pgdata:
  logs:
  pgadmin-data:
