"""First revision

Revision ID: 018ead8f4314
Revises: 
Create Date: 2024-01-03 16:59:50.296748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '018ead8f4314'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
