"""Locale deleted

Revision ID: 0ff9b5822dc8
Revises: 979ed33f6ac7
Create Date: 2024-01-14 08:26:23.188088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ff9b5822dc8'
down_revision = '979ed33f6ac7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_locale_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'locale_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('locale_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_locale_id_fkey', 'users', 'locales', ['locale_id'], ['id'])
    # ### end Alembic commands ###
