"""User achievement received at column

Revision ID: 979ed33f6ac7
Revises: e4e87fe9199c
Create Date: 2024-01-13 19:16:01.967390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '979ed33f6ac7'
down_revision = 'e4e87fe9199c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_achievements', sa.Column('received_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_achievements', 'received_at')
    # ### end Alembic commands ###
