"""Locale column nullable True

Revision ID: e4e87fe9199c
Revises: b1c8accff547
Create Date: 2024-01-13 17:05:22.662461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4e87fe9199c'
down_revision = 'b1c8accff547'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'locale_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'locale_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
